on: [push]

jobs:
  fail:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install minimal Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.45.2-x86_64-pc-windows-msvc
          profile: minimal
          components: clippy
      - uses: actions-rs/clippy-check@b5b5f21f4797c02da247df37026fcd0a5024aa4d
        # ----------------------------^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        # |
        # \ compare to upstream `master` branch at time of bug
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: fail-clippy-report
  fix:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install minimal Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.45.2-x86_64-pc-windows-msvc
          profile: minimal
          components: clippy
      - uses: ErichDonGubler/clippy-check@fix-windows-lf-breaking-reports
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: fix-clippy-report
